services:
  frontend:
    build:
      context: ./converter
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://127.0.0.1:8000/}
    container_name: converter
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE:-.env.development}
    depends_on:
      - backend

  backend:
    build:
      context: ./converter-api
    container_name: converter-api
    ports:
      - "8000:8000"
    environment:
      - UVICORN_WORKERS=4